---
title: "Billingsley Probability and Measure"
author: "AHC"
output: 
  pdf_document:
    extra_dependencies: ["amsthm", "amsmath"]
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newcommand{\mean}[1]{\bar{#1}}
\newcommand{\bb}[1]{\mathbb{#1}}
\newcommand{\ba}[1]{\begin{align}#1\end{align}}
\newcommand{\abs}[1]{\left\vert#1\right\vert}

\section{Chapter 1}
\textbf{1.1 a)}
We are to show that a countable probability space $\{\Omega, \mathbb{F}, P\}$ cannot have infinitely many independent events $A_1,A_2, \ldots$ each with probability $\frac{1}{2}$:

I think the key fact here is $P(\Omega) = 1 = \sum_{\omega \in \Omega}P(\omega)$, i.e. the measure of the tail $\Omega_n = \{\omega \in \Omega \vert n \ge N_\epsilon\}$ has probability less than $\epsilon$.
\begin{proof}
To have measure $\frac{1}{2}$, each $A_i$ must have non-empty intersection with a finite set $\Omega_{n < N_\epsilon}  = S \subsetneq \Omega$. Since since $P(A_i \cap A_j) = \frac{1}{4}$, the $A_i$ are distinct. On the other hand, since $P(A_i) = \frac{1}{2}$, they cannot differ only on $S^c$, as then the measure of their intersection would satisfy $P(A_i \cap A_J) > \frac{1}{2}-\epsilon > \frac{1}{4}$. For this we'd need countably infinitely many distinct subsets of $S$, but the power set of $S$ has cardinality $|P(S)| = 2^{|S|} < \infty$. 
\end{proof}

\textbf{1.1 b)}
Suppose that $0 < p_n < 1$, and put $a_n = \text{min}\{p_n,1 -p_n\}$. Show that, if $\sum_n a_n$
diverges, then no discrete probability space can contain independent events $A_1,A_2, \ldots$ such that $A_n$ has probability $p_n$. 

\begin{proof}
\color{red}{$\ldots$}
\end{proof}

\textbf{1.2}
Show that $N$ and $N^c$ are both dense in $(0,1]$. 
\begin{proof}
$N$ has Lebesgue measure 1, so it must intersect every open interval. On the other hand, every number $x \in N$ can be approximated arbitrarily well by terminating its decimal expansion.
\end{proof}

\textbf{1.3}

\textbf{a)} Show that a trifling set is negligible: \begin{proof} The trifling sets are a subset (the subset where the cover is finite) of the negligible sets.  \end{proof}
\textbf{b)} Show that the closure of a trifling set is also trifling.
\begin{proof}
Given $\epsilon > 0$, form a finite (say order $K$) $\frac{\epsilon}{2}$ cover, and then extend the endpoints of each covering interval out by $\frac{\epsilon}{5K}$ , and intersect these sets with $(0,1]$. The result is an (at maximum) $\frac{7}{10}\epsilon$ cover. 
\end{proof}
\textbf{c)} Find a bounded negligible set that is not trifling.
\begin{proof}
Consider $N^c$. This set has measure zero but is dense in $(0,1]$. So e.g. if $\epsilon < \frac{1}{2}$, there is no finite $\epsilon$ cover, as this would imply $N^c$ is compact, but $N^c$ is not closed, because it is dense in $(0,1]$ and hence its closure is $[0,1] \supsetneq N^c$.
\end{proof}
\textbf{d)}
Show that the closure of a negligible set may not be negligible.
\begin{proof}
See \textbf{c)} above.
\end{proof}
\textbf{e)} Show that finite unions of trifling sets are trifling but that this can fail for
countable unions.
\begin{proof}
For finite unions of order $K$, given $\epsilon > 0$, form $\frac{\epsilon}{2K}$ covers. On the other hand, $\mathbb{Q}\cap(0,1]$ is the countable union of its points, each of which as a set is trifling. $\mathbb{Q}\cap(0,1]$ is dense in $(0,1]$, so if it were trifling by part \textbf{b} $[0,1]$ would be trifling.
\end{proof}

\textbf{1.4} For $i=0, \ldots r-1$,let $A_r(i)$ be the set of numbers in $(0,1]$ whose non-terminating expansions in the base $r$ do not contain the digit $i$.

\textbf{a)} Show that $A_r(i)$ is trifling.
\begin{proof}
We observe $r=3,i=1$ yields the Cantor set. This gets our foot in the door for intuition, i.e. we can think of these sets via the construction "Remove the $i$-th $r$-rd of $(0,1]$. For each remaining subset, remove the $i$-th $r$-d. Repeat ad infinitum." 
If we consider the measure of the remaining set, at each stage we remove exactly $\frac{1}{r}$ of the remaining mass. Thus we have the sequence:
\ba{
\frac{r-1}{r}, \left(\frac{r-1}{r}\right)^2, \ldots
}
This sequence clearly converges to zero. We are to show that what remains is compact, which is wild as it's also uncountable, which we can observe by diagonalization of the set of r-expansions where $i$ never appears.
Given $\epsilon$, we can find $K_\epsilon = K$ such that at stage $K$, our approximation to $A_r(i)$ given by the first $K$ deletions has measure less than $ \frac{\epsilon}{2}$. These (finitely many) $N_K = N$ disjoint sub-intervals all have the same width by construction so each has width less than $\frac{\epsilon}{2N}$. We can then cover each with a ball of radius $\frac{3\epsilon}{4N}$.
\end{proof}

\textbf{b)} Find a trifling set $A$ such that every point in the unit interval can be represented in the form $x +y$ with $x$ and $y$ in $A$.

Playing with the Cantor set, for the first 3 iterations $C_1,C_2,C_3$, we can write any $z \in [0,1]$ as a sum of elements $x,y$ in $\{0\}\cup C_i$. Perhaps via induction we could show this property holds for all $C_i, i \in \mathbb{N}$. Assuming we can do this, does this imply the property holds in the limit? We know we can express any element in the limit via a base 3 expansion where $1$ never occurs. Perhaps we can construct $x$, $y$ from this fact? Consider $z=0.1$. In this case, we can take $x=0.02020\ldots$, $y=0.002020\ldots$. Really any partition of $0.022\ldots$ in $C$ will suffice. Perhaps we can generalize? Consider $z=0.111\ldots$. As a geometric series in base 3, this sums to $\frac{1}{3}\left( \frac{1}{1-\frac{1}{3}}\right)=\frac{1}{2}=0.1\left(\frac{1}{.222\ldots-0.1}\right)=\frac{0.1}{0.1222\ldots}=\frac{0.1}{0.2}$.
\begin{proof}
Okay let's try this: suppose $z$ has a $1$ in it's expansion base 3. We can generate this one via a carried $1$ from addition on the next digit. So then the question is, can we make the next digit whatever we want, given that we must generate a $1$ to carry? Well, if we need $0$, that's a $2$ and a one carried from the next digit. For a $1$, we can use two $2$'s. If we need a $2$, we can use two $2$'s a carry a one from the next digit. Each time we're forced to carry a digit, the logic we just used saves us. So the Cantor set suffices.
\end{proof}

\textbf{c)} (c) Let $A_r(i_1, \ldots , i_k )$ consist of the numbers in the unit interval in whose base-r expansions the digits $i_1, ... , i_k$ nowhere appear consecutively in that order. Show that it is trifling. What does this imply about the monkey that types at random?

\begin{proof} Firstly, awesome question. Secondly, once we note that $A_r(i_1,i_2)$ is isomorphic to $A_{r^2}(i_1i_2)$, and more generally  $A_r(i_1, \ldots , i_k ) \simeq A_{r^k}(i_1\cdots i_k)$ we see that this is an immediate consequence of part \textbf{a)}. 

For the monkey, this means that the Monkey will type all of literature. All the books that have been lost to time and all that could ever be written. The monkey will type them in all possible permutations, and all possible permutations of finitely many copies. What about infinitely many copies?
\end{proof}
